[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
arc_testnet = "${ARC_TESTNET_RPC_URL}"

[etherscan]
arc_testnet = { key = "${ARC_TESTNET_ETHERSCAN_API_KEY}", url = "https://api-testnet.arcscan.app/api" }

